//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionsManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mission
    {
        public int MissionId { get; set; }
        public string Mission_UserId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
        public string ResponsibilityUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
